storage:
  #存储方式 mysql:mysql数据库  h2:内存模式  sqlite:sqlite数据库
  type: mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/free_port_mapper?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
file-config:
  root: "D:\\data\\free_port_mapper"
  tmp: "temp"
  prefix: "{timestamp}"
web:
  export:
    #保存文件的文件夹绝对路径
    common-file-path: ${file-config.root}\\${file-config.tmp}
my-setting:
  password: root
